<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RabbitClient\Tests\ModuleTest'                              => __DIR__ . '/tests/RabbitClient/ModuleTest.php',
  'RabbitClient\Tests\TestAsset\Application'                   => __DIR__ . '/tests/RabbitClient/TestAsset/Application.php',
  'RabbitClient\Tests\Service\Factory\RabbitClientFactoryTest' => __DIR__ . '/tests/RabbitClient/Service/Factory/RabbitClientFactoryTest.php',
  'RabbitClient\Tests\BaseModuleTest'                          => __DIR__ . '/tests/RabbitClient/BaseModuleTest.php',
  'RabbitClient\Tests\Publisher\PublisherTest'                 => __DIR__ . '/tests/RabbitClient/Publish/PublisherTest.php',
  'RabbitClient\Tests\Bootstrap'                               => __DIR__ . '/tests/Bootstrap.php',
  'RabbitClient\Event\Listener'                                => __DIR__ . '/src/RabbitClient/Event/Listener.php',
  'RabbitClient\Service\Factory\RabbitClientFactory'           => __DIR__ . '/src/RabbitClient/Service/Factory/RabbitClientFactory.php',
  'RabbitClient\Service\Factory\RabbitClientSearchFactory'     => __DIR__ . '/src/RabbitClient/Service/Factory/RabbitClientSearchFactory.php',
  'RabbitClient\Service\Factory\RabbitClientImageFactory'      => __DIR__ . '/src/RabbitClient/Service/Factory/RabbitClientImageFactory.php',
  'RabbitClient\Service\Factory\RabbitClientService'           => __DIR__ . '/src/RabbitClient/Service/Factory/RabbitClientService.php',
  'RabbitClient\Publish\Publisher'                             => __DIR__ . '/src/RabbitClient/Publish/Publisher.php',
  'RabbitClient\Publish\PublisherSearch'                       => __DIR__ . '/src/RabbitClient/Publish/PublisherSearch.php',
  'RabbitClient\Publish\PublisherImage'                        => __DIR__ . '/src/RabbitClient/Publish/PublisherImage.php',
  'RabbitClient\Module'                                        => __DIR__ . '/Module.php',
);
